### PR TITLE
feat(android): upgrade Socket.IO client for server v3/v4 support

### LINKED ISSUE #31: Support for socket-io v3 and v4
Currently moko-socket-io uses [v1.0.0](https://github.com/icerockdev/moko-socket-io/blob/32ed1bcbfb92565702d1f053ed17ff216ff124df/gradle/libs.versions.toml#L4) of socket.io-client-java which is only [compatible upto v2 socket-io server](https://github.com/socketio/socket.io-client-java?tab=readme-ov-file#compatibility). 
Should update it to v2.x.x which adds support to v3 and v4

### PR DESCRIPTION
**Pull request by mrwhoknows55**
- Resolves connection issues with newer servers.
- Bump Android Socket.IO dependency to latest version.

Closes #31

### CODE REVIEW

**Review by Alex009 — APPROVED** [review]

**Comment by mrwhoknows55** [comment]
@Alex009 any updates on next release?

**Comment by OleksiiHromovych** [comment]
Any updates? I am interested in the socket server v3/v4. Thanks

**Comment by valeriyo** [comment]
@Alex009 can we get this merged/released?

**Review by Alex009 — APPROVED** [review]

**Review by Alex009 — APPROVED** [review]

**Comment by valeriyo** [comment]
🎉

**Pull request merged**
